
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";


export const metadata = {
  title: "Anam Developer",
  description: "Generated by Anam Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
