import Footer from "./Components/Footer/Footer";
import Navbar from "./Components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anam Developer",
  description: "Generated by Anam Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
